services:
  task_scheduler:
    build:
      context: ./task_scheduler
      dockerfile: Dockerfile
    container_name: task_scheduler
    ports:
      - "38080:8080"
    volumes:
      - ./logs/:/logs/